name: Merge post feature branch to main
on:
  pull_request:
    branches: [ "main", "**/post**"]
    paths:
      - 'post_management/**'
    
jobs:
  test_posts:
    runs-on: ubuntu-latest
    services:
      post_db_test:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: post_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U post_db_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        working-directory: ./post_management
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./post_management
        run: pipenv install --dev

      - name: Wait for Postgres
        run: until pg_isready -h localhost -U post_db_test -p 5432; do sleep 1; done
        working-directory: ./post_management

      - name: Run unit tests
        working-directory: ./post_management
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70